name: Private Cloud Factory CI
on:
  schedule:
    - cron: '0 7,15 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_ORG_NAME: wm-private-cloud-test
  TEST_REPO_NAME: factory-test-${{ github.run_number }}
  DEPLOYMENT_RELEASE_NAME: factory-test-${{ github.run_number }}
  DOCKER_IMAGE_NAME: "msr:factory-test"
jobs:
  create-private-cloud-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Get GitHub App Token
        id: action-github-app-token
        uses: actions/create-github-app-token@v1.9.3
        with:
          app-id: ${{ secrets.FACTORY_TEST_APP_ID }}
          private-key: ${{ secrets.FACTORY_TEST_APP_PEM }}
          github-api-url: "https://api.github.com"
          owner: "${{ env.TEST_ORG_NAME }}"
          repositories: "private-cloud-factory-test"
          
      - name: Create Repository from Factory Template
        run: |
          curl -L -f \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.action-github-app-token.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/wm-private-cloud/private-cloud-factory/generate \
          -d '{"owner":"${{ env.TEST_ORG_NAME }}","name":"${{ env.TEST_REPO_NAME }}","description":"Test Factory Repository","include_all_branches":false,"private":false}'

      
  trigger-cicd-worfklow:
    runs-on: ubuntu-latest
    needs: create-private-cloud-repository
    strategy:
      matrix: # Ensure idempotent execution by running the workflow 2 times with the same data. In this case the second run should just update the deployment and finish successfully, too
        workflow-run-index: [0, 1]
      max-parallel: 1 # Ensure the runs are sequential even if there is more than one runner available
    steps:
      - name: Get GitHub App Token
        id: action-github-app-token-test-repo
        uses: actions/create-github-app-token@v1.9.3
        with:
          app-id: ${{ secrets.FACTORY_TEST_APP_ID }}
          private-key: ${{ secrets.FACTORY_TEST_APP_PEM }}
          github-api-url: "https://api.github.com"
          owner: "${{ env.TEST_ORG_NAME }}"
          repositories: "${{ env.TEST_REPO_NAME }}"
          
      - name: Trigger CI/CD Workflow
        run: |
          # For now just wait 50 seconds to have GitHub properly setup the repository. Improve by adding polling 
          sleep 50
          curl -L -f \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.action-github-app-token-test-repo.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.TEST_ORG_NAME }}/${{ env.TEST_REPO_NAME }}/actions/workflows/cicd.yml/dispatches \
          -d '{"ref":"main","inputs":{"dockerImage":"${{ env.DOCKER_IMAGE_NAME }}","wmPackages":"WmJDBCAdapter","customPackages":"Fibonacci","customPackagesOrgUrl":"https://github.com/wm-private-cloud-test","deploymentReleaseName":"${{ env.DEPLOYMENT_RELEASE_NAME }}"}}'
      
      - name: Wait for Workflow Completion
        run: |
          echo "|Check|Status|" >> $GITHUB_STEP_SUMMARY
          echo "|:-:|:-:|" >> $GITHUB_STEP_SUMMARY
          url="https://api.github.com/repos/${{ env.TEST_ORG_NAME }}/${{ env.TEST_REPO_NAME }}/actions/runs"
          interval=10
          timeout=$((30 * 60))
          startTime=$SECONDS
          
          while true; do
              elapsedTime=$((SECONDS - startTime))
              if [ "$elapsedTime" -ge "$timeout" ]; then
                  echo "Timeout reached after $((elapsedTime / 60)) minutes. Exiting with status 1."
                  echo "|CICD Workflow successful|:alarm_clock:|" >> $GITHUB_STEP_SUMMARY
                  exit 1
              fi
              response=$(curl -L -f -X GET -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.action-github-app-token-test-repo.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" "$url")
              status=$(echo "$response" | jq -r '.workflow_runs[${{ matrix.workflow-run-index }}].status // empty')
              conclusion=$(echo "$response" | jq -r '.workflow_runs[${{ matrix.workflow-run-index }}].conclusion // empty')
              if [ "$status" == "completed" ]; then
                  echo "Status is completed for the ${{ matrix.workflow-run-index }} workflow run."
                  if [ "$conclusion" == "success" ]; then
                      echo "Conclusion is success. Exiting with status 0."
                      echo "|CICD Workflow successful|:white_check_mark:|" >> $GITHUB_STEP_SUMMARY
                      exit 0
                  else
                      echo "Conclusion is $conclusion. Exiting with status 1."
                      echo "|CICD Workflow successful|:x:|" >> $GITHUB_STEP_SUMMARY
                      exit 1
                  fi
              fi
              echo "Status is $status for the ${{ matrix.workflow-run-index }} workflow run. Retrying in $interval seconds..."
              sleep "$interval"
          done

  verify-successful-image-creation:
    runs-on: ubuntu-latest
    needs: trigger-cicd-worfklow
    steps:
      - name: Check image 
        run: |
          echo "|Check|Status|" >> $GITHUB_STEP_SUMMARY
          echo "|:-:|:-:|" >> $GITHUB_STEP_SUMMARY
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ vars.DOCKER_REGISTRY }}
          expectedImage=${{ vars.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}
          docker pull $expectedImage && echo "|Expected $expectedImage image available|:white_check_mark:|" >> $GITHUB_STEP_SUMMARY || (echo "|Expected $expectedImage image available|:x:|" >> $GITHUB_STEP_SUMMARY && exit 1)
          
        
  verify-successful-deployment:
    runs-on: ubuntu-latest
    needs: trigger-cicd-worfklow
    env:
      KUBECONFIG: ${{ github.workspace }}/${{ github.run_number }}-kubeconf
    steps:
      - name: Authenticate against Kubernetes cluster
        run: echo "${{ secrets.KUBE_CONFIG }}" > ${KUBECONFIG}
        
      - name: Check deployment status
        run: |
          echo "|Check|Status|" >> $GITHUB_STEP_SUMMARY
          echo "|:-:|:-:|" >> $GITHUB_STEP_SUMMARY
          (helm status ${{ env.DEPLOYMENT_RELEASE_NAME }} | grep "STATUS: deployed") && (echo Successful verification && echo "|Deployed application|:white_check_mark:|" >> $GITHUB_STEP_SUMMARY) || (echo Verification failed - deployment status is not "deployed" && echo "|Deployment status|:x:|" >> $GITHUB_STEP_SUMMARY && exit 1)
      
      - name: Check endpoint running and installed packages
        run: |
          echo "|Check|Status|" >> $GITHUB_STEP_SUMMARY
          echo "|:-:|:-:|" >> $GITHUB_STEP_SUMMARY
          LOCAL_PORT=`expr ${{ github.run_number }} + 5000`
          export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=microservicesruntime,app.kubernetes.io/instance=${{ env.DEPLOYMENT_RELEASE_NAME }}" -o jsonpath="{.items[0].metadata.name}")
          export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
          kubectl --namespace default port-forward $POD_NAME $LOCAL_PORT:$CONTAINER_PORT &
          BASE_URL="http://localhost:$LOCAL_PORT"
          URL=$BASE_URL
          TIMEOUT=300
          INTERVAL=5
          check_endpoint() {
            STATUS_CODE=$(curl --silent --insecure --write-out "%{http_code}" --output /dev/null --user "${{ secrets.APP_USERNAME }}:${{ secrets.APP_PASSWORD }}" "$URL")
            echo "Current status code is $STATUS_CODE"
            if [ "$STATUS_CODE" -eq 200 ]; then
              return 0
            else
              return 1
            fi
          }  
          echo "Starting polling..."
          START_TIME=$(date +%s)
          while ! check_endpoint; do
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            if [ "$ELAPSED_TIME" -ge "$TIMEOUT" ]; then
              echo "Timeout reached. Service is not available at $URL"
              echo "|Application running on $URL|:x:|" >> $GITHUB_STEP_SUMMARY
              exit 1
            fi
            echo "Waiting for the service to start... ($ELAPSED_TIME seconds elapsed)"
            sleep "$INTERVAL"
          done
          echo "Service is up and running at $URL"
          echo "|Application running on $URL|:white_check_mark:|" >> $GITHUB_STEP_SUMMARY

          URL=${BASE_URL}/admin/package/Fibonacci
          if check_endpoint; then
            echo "Custom Fibonacci package is available"
            echo "|Custom Fibonacci package is available at $URL|:white_check_mark:|" >> $GITHUB_STEP_SUMMARY
          else
            echo "Custom Fibonacci package is NOT available"
             echo "|Custom Fibonacci package is available at $URL|:x:|" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

          URL=${BASE_URL}/admin/package/WmJDBCAdapter
          if check_endpoint; then
            echo "WmJDBCAdapter package is available"
             echo "|WmJDBCAdapter package is available at $URL|:white_check_mark:|" >> $GITHUB_STEP_SUMMARY
          else
            echo "WmJDBCAdapter package is NOT available"
            echo "|WmJDBCAdapter package is available at $URL|:x:|" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          

      - name: Cleanup deployment
        if: always()
        run: helm uninstall ${{ env.DEPLOYMENT_RELEASE_NAME }} || true
        
      - name: Cleanup runner
        if: always()
        run: rm -rf ${KUBECONFIG}
           
  cleanup-private-cloud-repository:
    if: always() #TODO: For now always delete, then delete only on success
    runs-on: ubuntu-latest
    needs: [verify-successful-deployment, verify-successful-image-creation]
    steps:
      - name: Get GitHub App Token
        id: action-github-app-token-test-repo
        uses: actions/create-github-app-token@v1.9.3
        with:
          app-id: ${{ secrets.FACTORY_TEST_APP_ID }}
          private-key: ${{ secrets.FACTORY_TEST_APP_PEM }}
          github-api-url: "https://api.github.com"
          owner: "${{ env.TEST_ORG_NAME }}"
          repositories: "${{ env.TEST_REPO_NAME }}"
          
      - name: Delete Repository
        run: |
          curl -L -f \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ steps.action-github-app-token-test-repo.outputs.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.TEST_ORG_NAME }}/${{ env.TEST_REPO_NAME }} 
 
  notify-on-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: cleanup-private-cloud-repository
    steps:
      - name: Notify
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: "[FAILURE] Private Cloud Factory Test"
          notification-color: d60c36
          timezone: Europe/Sofia
          verbose-logging: true
